service: drone-monorepo-plugin

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:DescribeParameters"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/GITHUB_TOKEN"
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/DRONE_PLUGIN_SECRET"

functions:
  droneListener:
    handler: index.handler
    events:
      - http:
          path: webhook
          method: post

custom:
  webpack:
    includeModules: true
    packager: "yarn"
